### ISSUE TITLE
Problems with favourites in GNOME

### ISSUE THREAD

**Issue by raczkow** [MrCarroll/joplin-desktop-snap#14]
Last release of joplin-desktop has issue with favourites in GNOME. You can't pin it to tasks bar:

![obraz](https://user-images.githubusercontent.com/24735616/110636335-70195b00-81ac-11eb-8b8f-2c698f0ccee0.png)

I've found the problem: there is a wrong file: /var/lib/snapd/desktop/applications/joplin-desktop_joplin.desktop

It should be named: /var/lib/snapd/desktop/applications/joplin-desktop_**joplin-desktop**.desktop with the following change in the content:

```
- Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/joplin-desktop_joplin.desktop /snap/bin/joplin-desktop
+ Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/joplin-desktop_joplin-desktop.desktop /snap/bin/joplin-desktop
```
With that change, pinnging to task bar works:

![obraz](https://user-images.githubusercontent.com/24735616/110636943-2da44e00-81ad-11eb-8c00-50e2c97f0ab5.png)

"Dodaj do ulubionych" -> "Add to favourites" (I've got Polish locale)

**Comment by JGCarroll** [comment]
Thanks for the info

I can reproduce this on my side but I can't determine what the problem is. Whilst I provide a template for snapd to generate a valid desktop file from, it's snapd itself that's actually in charge of putting the file in the right place, with the correct hints.

I'll look around some more and see if I can dig up what might be causing the underscore to be replaced with the full-stop / period but my current guess is that it might be something subtle in snapd itself.

**Comment by JGCarroll** [comment]
Actually, I wonder if this is as simple as the fact the snap has `-desktop` as part of it's name, it doesn't appear in `joplin-james-carroll`, the legacy package.

I'm suspicious this is a new regression upstream.

**Comment by raczkow** [comment]
Are you able to change name of the file: /snap/joplin-desktop/current/meta/gui/joplin.desktop to joplin-desktop.desktop?
Maybe that would fix the problem?

**Comment by JGCarroll** [comment]
Amazing! That actually does the job just fine :)! Thanks for the suggestion.

I've rebuilt and published the snap now, if you run `sudo snap refresh` it should hopefully fix the problem for you.

**Comment by raczkow** [comment]
Works like a charm :-)
Thanks for a great job!
