### ISSUE TITLE
Remove explicit libappindicator dependency

### ISSUE THREAD

**Issue by 3v1n0** [MrCarroll/joplin-desktop-snap#15]
https://github.com/MrCarroll/joplin-desktop-snap/blob/4ce04c742a7830dbf440a56493148d6e51e74d9b/snap/snapcraft.yaml#L33

It's already part of the GNOME extension

```
❯ find /snap/gnome-3-38-2004|grep libappindica 
/snap/gnome-3-38-2004/39/usr/lib/x86_64-linux-gnu/libappindicator3.so.1
/snap/gnome-3-38-2004/39/usr/lib/x86_64-linux-gnu/libappindicator3.so.1.0.0
```

You test this in an override scriptlet to ensure it will be always there...

**Comment by JGCarroll** [comment]
Including it ensures it's dependencies will be shipped, which might not necessarily be included in the Gnome extension, but the parts that do overlap won't take space because of the cleanup scriptlet.

I've tried to test removing it now regardless to see if it's actually possible, but I'm having some unrelated issues with building so can't confirm it right now. In the worst case the line does nothing, but it does guarantee a lot by being there.

**Comment by JGCarroll** [comment]
Having actually tested it, it works absolutely fine and saves 20MB of space in the snap. Thanks for the suggestion!

https://github.com/MrCarroll/joplin-desktop-snap/commit/3e0b39c89df9aeb97f47fdd23e7d4116ff1076d8
