### ISSUE TITLE
cannot find app "joplin-james-carroll"

### ISSUE THREAD

**Issue by samtuke** [MrCarroll/joplin-desktop-snap#2]
I'm getting this error:

`error: cannot find app "joplin-james-carroll" in "joplin-james-carroll"`

Installed version 1899d866.

**Comment by JGCarroll** [comment]
How exactly is it being run?  If it's via the terminal, the command would be either `joplin-james-carroll.joplin` or `snap run joplin-james-carroll.joplin`

If it's via the desktop icon I'll be sure to take a look at this urgently later today

**Comment by samtuke** [comment]
That works! Thanks for the fast reply. I previously guessed and tried:

```
snap run joplin-james-carroll
snap run joplin-james-carroll.app
snap run joplin
```

I'm on Fedora 31 and snap apps aren't added to the launcher automatically, so using `snap run` is always required in my case.

Please consider adding those commands to the Snap description on snapcraft.

**Comment by JGCarroll** [comment]
For future reference, you can use the `snap info` command to aid here, so `snap info packagename` would list all the apps associated with that package name. You can also make your life more convienient by aliasing them at the Snap level, so something like `sudo snap alias joplin-james-carroll.joplin joplin` should make it run with just `snap run joplin` thereafter.

Snaps should generally be added to the launcher automatically, if they're not, it's usually a problem with XDG_DATA_DIRS not being set, often when Bash isn't the default login shell. You can find more info here https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1640514 and the fix is to essentially just make sure the variable is set correctly during the login script. 

I'll add the snap run command to the web store UI since it won't really add much in terms of space.
