### ISSUE TITLE
Snapcraft release is outdated

### ISSUE THREAD

**Issue by mcmxcdev** [MrCarroll/joplin-desktop-snap#20]
I noticed that the https://snapcraft.io/joplin-desktop latest release still points to v2.7.14, while the master commit history includes "Update to 2.8.7". 

What does it take to get the snapcraft release synced up with 2.8.7 (now even 2.8.8)?

**Comment by JGCarroll** [comment]
The 2.8 series hasn't been marked as stable upstream yet, and upstream has asked downstream to not release beta packages unless they're clearly separated as pre-release channels. While snaps can do this pretty well, I'm not keen to start doing it because based on my other packages there's usually not much benefit in terms of feedback.

There'll also be a longer than usual rollout for 2.8 because I've added a minimum version requirement for snapd itself that hasn't yet released, although I don't expect this to be the case for more than a week or so.

**Comment by mcmxcdev** [comment]
Ohhh, I didn't notice the pre-release label on the tags, all clear thanks!
