### ISSUE TITLE
HTML export error ENOENT

### ISSUE THREAD

**Issue by ggaessler** [MrCarroll/joplin-desktop-snap#22]
see https://github.com/laurent22/joplin/issues/6971

@laurent22 said
> Looks like it should be reported to the Snap package maintainer.

Might be related to https://github.com/MrCarroll/joplin-desktop-snap/issues/18

**Comment by JGCarroll** [comment]
Hey,

The other issues are still myserious as I can't reproduce them, but the output from your linked issue actually has something I've picked up on as being very perculiar.

Specifically, the top line:

```
InteropService.ts:444 Error: ENOSYS: function not implemented, mkdir '/run/user/1508765214/doc/a0233181/pluginAssets'
```

Particularly regarding
```
/run/user/1508765214
```

The number there is supposed to reflect the User ID of the user on the system, e.g, the first non-system user on most non-networked systems is usually `1000`, so the line above would suggest your system has another one and a half billion users. Or less ridiculously, there's likely something going on with determining the UID, the UID is being randomised, the UID is in a namespace, or anything else other than you have one and a half billion accounts!

Could you please try a basic test, opening the terminal, and running

```
echo $UID
snap run --shell joplin-desktop
echo $UID
exit
```

Ultimately, the files are ending up in `/run` since Electron is using the XDG Desktop FileOpen portals. Judging that these errors didn't occur until relatively recently, I'm imagining something may have changed in Electron or the Portals, with Electron being more likely. There's a fairly large jump in Electron versions in the Joplin 2.9 release that's due soon, and it's possible that this may fix the problem.

**Comment by ggaessler** [comment]
Thanks for the quick response! Yes, the user id is correct and also reported by the `echo $UID``, both within and outside of the snap shell. The shell prints:
````
groups: cannot find name for group ID 1508765214
groups: cannot find name for group ID XXXXXXXX
[...]
I have no name!@MYCOMPUTERNAME:/home/MYUSERNAME$
````
I agree that this setup is pretty specific. In case that's likely to change with 2.9 it would also be fine for me to wait whether that might fix it.

**Comment by JGCarroll** [comment]
Are you logging into a networked system by any chance? Would you also be able to run `id` in bash and post the results?

The UID/GID being big shouldn't cause problems by itself, but the "cannot find name for group ID" is concerning. Groups usually are listed in `/etc/group` on non-networked systems, so it'd be expected you'd get a hit for e.g:

```
grep "1508765214" /etc/group
```

Presumably on your system, it'll return nothing. It could be worth trying to add a group with that name, but it's still difficult to determine why (or if) there's a relation between the group setup and the errors being returned. 

If there isn't a group you could consider:

```
sudo addgroup --gid 1508765214 xdg-portal-workaround
sudo groupadd $USER xdg-portal-workaround
```

But ultimately I'm feeling this issue is actually slightly distinct from the other two issues involving exports, and might be more of a system configuration problem than implementation problem from what it looks like so far.

**Comment by ggaessler** [comment]
Thanks a lot for the support so far. I didn't think that this issue might be caused by the network setup of the machine, otherwise I wouldn't have opened it. User accounts are managed via SSSD and LDAP. And as much as I'd like to see this issue fixed I'm afraid I can't share any further details of the specific setup, I'm sorry. Since this issue might be very specific to my setup and not affect many other users I'd close it therefore even though not all information can be provided to solve the real cause.

**Comment by JGCarroll** [comment]
No worries, it's a shame but there's a few concessions.

This issue would probably effect you less on Ubuntu 22.04 (due to newer `xdg-desktop-portal` packages). If you're trying to export to $HOME, in 22.04, the portals wouldn't use the indirection through `/run/user`, which I assume would bypass this problem.

Similarly, the Joplin Flatpak wouldn't suffer this issue (even in 20.04), and neither would the AppImage.

The data format shoudl be identical between all 3, so if you fancied transfering over to the AppImage/Flatpak, you should be able to copy and paste the folders in `$HOME/snap/joplin-desktop/` over to the equivilent's in `$HOME`; or export as Jex and re-import, use built syncronisation, etc.
