### ISSUE TITLE
Snap version of joplin-desktop would not open

### ISSUE THREAD

**Issue by cdamyx** [MrCarroll/joplin-desktop-snap#23]
Hi there!

I've been using the snap version of joplin-desktop for a couple of years - thanks for your contribution!

I was unable to open Joplin today, and found [this issue](https://github.com/laurent22/joplin/issues/4646). My comment at the bottom helped me resolve. Thought I would bring it to your attention, as well :smiley: 

Cheers!

**Comment by JGCarroll** [comment]
Thanks for the info.

I publish one snap `joplin-desktop` and the other `joplin-james-carroll` (the original name). The one with my name is created from the other one by modifying the others metadata but otherwise they're bit for bit identical.

For some reason when I've tried testing that again now it's not working how I expect causing the `exec=` line to go missing, I'll rebuild and publish a patch in the next hour or so.

**Comment by JGCarroll** [comment]
The fix is uploaded now and effected people should have the desktop icon working again once they receive the update.

Thanks again for your help.

**Comment by cdamyx** [comment]
Awesome, thank you @MrCarroll!
