### ISSUE TITLE
Add `StartupWMClass=Joplin` to enable tray icon

### ISSUE THREAD

**Issue by alexanderadam** [MrCarroll/joplin-desktop-snap#4]
The tray icon isn't working for be and according to [this comment](https://github.com/laurent22/joplin/issues/86#issuecomment-376811132) it should work by adding `StartupWMClass=Joplin` to [the desktop file](https://github.com/MrCarroll/joplin-snap/blob/master/snap/gui/joplin.desktop).

I would love to test it first but I'm unable to find the desktop file. :thinking: 
I think it could be `/snap/joplin-james-carroll/20/meta/gui/joplin.desktop` but I can't write in the file.

**Comment by JGCarroll** [comment]
All the contents in `/snap/` are read only because they're mounted from the singular squashfs .snap file that snaps are distributed as. The desktop file you've spotted is the exact same one as in this repo, and when a snap is installed snapd reads it and runs it through a small script that checks its integrity, transforms it a little, and ultimately puts the desktop file that your system tray actually uses in `/var/lib/snapd/desktop/applications`, you should be able to actually edit the desktop file in that folder and find the changes actually take effect.

If that one line is all that's needed to get it working for you, I can have it shipped with stable really quickly.

**Comment by alexanderadam** [comment]
Interesting. It doesn't seem to work for me though.
Are you seeing the Joplin tray icon when you're running Joplin?

**Comment by JGCarroll** [comment]
Setting the WM class in the desktop file wasn't enough for me to get the tray icon to work by itself.

From what I can tell, Joplin does set its own WM_CLASS properly without the value set in the desktop file. I've added it into the desktop file anyway, no harm in being thorough.

The reason the tray icon wasn't appearing is because it was being blocked by the snapd sandbox, specifically the org.kde.StatusNotifierWatcher interface via DBus was being blocked. Adding the unity7 interface to the snap fixes this problem (and in the future, it should be allowed by the desktop-legacy interface too, according to https://forum.snapcraft.io/t/solved-remmina-notification-icon-problem/17892/9 )

This is enough to get the tray icon to appear, but the right click options of open and quit don't seem to be functional. I'll spend some more time on seeing if I can figure out why.

Try updating the snap with `sudo snap refresh` (preferably with it not running), once it's updated; untick the show tray icon, apply it, exit Joplin and reopen it, when you re-enable show a tray icon it should work with the caveats of the right click options not being visible.

**Comment by alexanderadam** [comment]
James that's awesome!
Thank you for your snap packages, for being so helpful and responsive. :pray:

**Comment by JGCarroll** [comment]
Thanks for the positivity :)!

I've been looking into how this works. From what I can tell, Electron prior to version 8 used libappindicator for tray icons in Linux. In version 8 it transitioned to using dbus / dbusmenu instead of libappindicator. Joplin is currently on version 8 of Electron.

In Electron 9, which has been out a few months already; Electron reverts back to the legacy behaviour of using libappindicator.

As of right now, the snapd sandbox blocks the dbus calls necessary to get the right clicks functional. It would be possible to fix this by adding the right Apparmor rules into snapd upstream, but for that fix to be distributed to everyone they'd need to upgrade snapd. Snapd updates itself in a lot of situations, is kept up to date by the distribution maintainers in other situations, but sometimes is kept held back for whatever reasons. Regardless, this means that the fix for this in the case of Electron 8 isn't something I can personally do, it needs to be done with snapd itself. There might be reasons this behaviour is blocked already I'm not sure about (information disclosure or sandbox escape or something similar), or it might just be an oversight, but there'd need to be request for it there.

However, in the case of Electron 9, I think it is entirely within my realm of control, and so it's just a waiting game of Joplin updating to it in the future.

**Comment by alexanderadam** [comment]
Oh wow, okay. I guess I close this issue then if there's nothing fixable in joplin-snap.
Thank you again :+1:

**Comment by JGCarroll** [comment]
Joplin 1.4 is upgraded to an Electron 10 base and the snap now has libappindicator bundled, meaning the full icon functionality works in the newest releases. (Tested on Ubuntu 20.04 / Gnome 3.36).

**Comment by alexanderadam** [comment]
I don't know whether I mentioned this earlier but you're an awesome Snap maintainer. 
Thank you so much for your updates.
