### ISSUE TITLE
Snap 1.0.242 doesn't start (on Wayland?)

### ISSUE THREAD

**Issue by Hooloovoo** [MrCarroll/joplin-desktop-snap#5]
Hello,

I just tried the snap of Joplin available in the store:
https://snapcraft.io/joplin-james-carroll
(currently 1.0.242)

Clicking the icon does nothing. Trying to start it from the commandline gives:
$ joplin-james-carroll.joplin 
(joplin:32433): Gtk-WARNING **: 11:58:50.880: cannot open display: :0

I am using Wayland on 20.04 if that makes any difference.

The 1.0.241 AppImage available on https://joplinapp.org/ launches fine.

**Comment by JGCarroll** [comment]
Thanks for the information.

Joplin being an Electron app doesn't have native Wayland support at the moment and falls back to using XWayland. This is a special case for Snaps because of how they interact with environment variables and this is why it doesn't work. Interestingly I'd naively assumed this wasn't the case because there's a substantial amount of users on Fedora which is Wayland by default, but then in that environment things aren't as clear due to a different sandbox backend that means they might work with XWayland fine anyway.

Luckily it's a one line fix for me and I've uploaded a build with it now that I think should sort it out.

If you run `sudo snap refresh` in the terminal to update to the latest release I think everything should be sorted for you.

cbce52aa85a98a408d8d231a8cab8b1d5433c843
