### ISSUE TITLE
Snap 1.0.245 note viewer glitches

### ISSUE THREAD

**Issue by ghost** [MrCarroll/joplin-desktop-snap#6]

**Comment by JGCarroll** [comment]
Thanks for the information.

From the sounds of these bugs, they'd probably effect Joplin outside the Snap environment. Could you give the upstream official AppImage a go and see if you can reproduce the issues? You can download the AppImage here 
https://github.com/laurent22/joplin/releases/tag/v1.0.245

If they occur in the AppImage too, then the best place to report them would be to the upstream repository itself, https://github.com/laurent22/joplin

For the most part, I'd expect these snap Joplin builds to function identically to the official builds except where the snapd sandbox causes issues, the first issue looks as if its something entirely in upstreams control. The second issue with the white flashes is likely in upsteams control. It could be a specific snap issue regarding GPU drivers or something similar I might be able to do something with, but it wouldn't be my first guess. You could also try removing the GPU permission from the snap via the preferences button in the Ubuntu Software app; forcing it to go back to CPU rendering. You'd usually expect this to perform worse, but if the problem is in the graphics acceleration, it might be beneficial here.

You can also remove the GPU permission via the terminal with `sudo snap disconnect joplin-james-carroll:opengl :opengl` and give it back with `sudo snap connect joplin-james-carroll:opengl :opengl`

**Comment by GingerPapa** [comment]
Hi,
I encountered the same issues in the AppImage and I've opened another issue in the main Joplin repository. Thank you for explaining though!
