### ISSUE TITLE
install problem on Ubuntu 20.04

### ISSUE THREAD

**Issue by skiwichu** [MrCarroll/joplin-desktop-snap#8]
Hi, Joplin stop working after the latest update on Ubuntu 20.04. If I try to reinstall I got this error message:
```bash
$ sudo snap install joplin-james-carroll                                                                       
error: cannot perform the following tasks:                                                                                          
- Run configure hook of "joplin-james-carroll" snap if present (run hook "configure":           
-----                                                                                                                               
cannot update snap namespace: remove /usr/bin/gjs: read-only file system                    
snap-update-ns failed with code 1: File exists
-----)
```
Downloading and installing AppImage from joplin.org works like a charm. Testing Joplin v1.3.18.

Cheers!

**Comment by JGCarroll** [comment]
Thanks for the report.

This seems like an error with snapd more than it does with this particular snap but I can try to help anyway, could you give the output of running this in the terminal please?

`SNAPD_DEBUG=1 SNAP_CONFINE_DEBUG=1 sudo snap install joplin-james-carroll`

It sounds like something that might be beyond my expertise to look into but I can give it a go and failing that try get the attention of someone with more knowledge on this particular bit of snapd.

**Comment by skiwichu** [comment]
It exactly returns the same:/ I'll try to check the web about the error as well.

**Comment by skiwichu** [comment]
The only useful stuff I've found is <https://forum.snapcraft.io/t/snap-layouts/7207/30>. Not sure, if it can be helpful.

**Comment by MrCarroll** [comment]
I'll post on the Snapcraft forums (same forums as the one you've linked above) asking for someone with more explicit knowledge to take a look here, if it's effecting you, it's likely it would affect other people too so it probably deserves the some attention from upstream. Hopefully someone will take a look at it when they have some time free.

I'm unsure if there's a layout entry for gjs, some entries are automatically added because the gnome extensions transparently make modifications, but I don't expect that to be the problem, but I'll inspect in a few hours when I have access to a computer.

In the meantime could you give the output of `snap version` so it's explicit which version of snapd is running.

**Comment by JGCarroll** [comment]
I'll post on the Snapcraft forums (same forums as the one you've linked above) asking for someone with more explicit knowledge to take a look here, if it's effecting you, it's likely it would affect other people too so it probably deserves the some attention from upstream. Hopefully someone will take a look at it when they have some time free.

I'm unsure if there's a layout entry for gjs, some entries are automatically added because the gnome extensions transparently make modifications, but I don't expect that to be the problem, but I'll inspect in a few hours when I have access to a computer.

In the meantime could you give the output of `snap version` so it's explicit which version of snapd is running.

Edit: it's probably also worth checking to see what other snaps are functional, particularly if it might only be a problem with snaps with configure hooks. Could you try:

`sudo snap install hello-world`
`sudo snap install chromium --beta`

If there was any notes in Joplin, they should hopefully be backed up by snapd snapshots, so you should be able to recover them, I think the `snap saved` command could help there.

**Comment by skiwichu** [comment]
```
$ snap version
snap    2.47.1+20.04
snapd   2.47.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-53-generic
```
```hello-world``` as well as ```chromium``` have been installed without a problem.

I haven't got problem with notes. There are backed up on OneDrive using several apps to sync them. Anyway, thanks for nudging ```snap saved``` command. I'm not an expert in snapcraft.

**Comment by skiwichu** [comment]
Shite, I tried another reboot just to be sure, (I definitely did another one before) and now it installed well... no idea, why it's happened. so, it's probably solved now. kinda weird. thanks for swift replies.

**Comment by JGCarroll** [comment]
Computers doing what computers do best I see, a classic!

Hopefully everything is working as expected now then. I assume snap might have restored your notes automatically but if you have backups synced anyway then I suppose it's not super important.

Cheers!
